### ISSUE TITLE
Problem with gcc and staticExec

### ISSUE THREAD

**Issue by nintyfan** [moigagoo/nimage#34]
In docker container, when I try to invoke staticExec, error appears like:
gcc: no such command: /bin/sh

**Comment by moigagoo** [comment]
What command are you trying to execute?

**Comment by nintyfan** [comment]
> What command are you trying to execute?

pkgconfig . It's missing in the image. So, that's the problem?

**Comment by moigagoo** [comment]
> pkgconfig . It's missing in the image. So, that's the problem?

It's very hard to tell since I don't know what you're trying to achieve.

`staticExec` just executes a command in the shell at compile time. If it runs without Nim, it will run with `staticExec`.

`pkgconfig` is not included in the image, so obviously you can't run it. It has nothing to do with the Nim image though.

`staticExec` per se works just fine:
```
root@7bff24481e70:/usr/src# cat se.nim
const lsRoot = staticExec "ls /"
echo lsRoot

root@7bff24481e70:/usr/src# nim r se.nim
Hint: used config file '/nim/config/nim.cfg' [Conf]
Hint: used config file '/nim/config/config.nims' [Conf]
....CC: se.nim

Hint:  [Link]
Hint: 22160 lines; 0.654s; 26.301MiB peakmem; Debug build; proj: /usr/src/se.nim; out: /root/.cache/nim/se_d/se [SuccessX]
Hint: /root/.cache/nim/se_d/se  [Exec]
bin
boot
dev
etc
home
lib
lib32
lib64
libx32
media
mnt
nim
opt
proc
root
run
sbin
srv
sys
tmp
usr
var
```
